name: Publish Library

on:
  workflow_run:
    workflows: [Scala CI]
    types: [completed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - uses: actions/checkout@v5
    
    - name: Set up JDK 11
      uses: actions/setup-java@v5
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
        
    - name: SBT Publish
      run: sbt publish
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
