name: Publish Tamaki twalgor

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v5
      with:
        repository: twalgor/tw
    - name: Set up JDK 11
      uses: actions/setup-java@v5
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Create pom.xml file
      run: |
          cat <<EOF > pom.xml
          <project>
          <modelVersion>4.0.0</modelVersion>
          <groupId>twalgor</groupId>
          <artifactId>tw</artifactId>
          <version>1</version>
          <properties>
               <maven.compiler.source>11</maven.compiler.source>
               <maven.compiler.target>11</maven.compiler.target>
          </properties>
          <distributionManagement>
          <repository>
            <id>github</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/michel-medema/scala-graph-tools</url>
          </repository>
          </distributionManagement>
          </project>
          EOF
          
    - name: Alter the directory structure.
      run: mkdir -p ./src/main/java && mv ./src/io ./src/main/java/io

    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
