name: Publish Library

on:
  workflow_run:
    workflows: [Scala CI]
    types: [completed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v5
    
    - name: Set up JDK 19
      uses: actions/setup-java@v5
      with:
        java-version: '19'
        distribution: 'temurin'
        cache: 'sbt'

    - uses: sbt/setup-sbt@v1
        
    - name: SBT Publish
      run: sbt publish
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
